export const CREATE_ADMIN_START = 'CREATE_ADMIN_START'
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS'
export const CREATE_ADMIN_FAILURE = 'CREATE_ADMIN_FAILURE'

export const CREATE_COMPANY_START = 'CREATE_COMPANY_START'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE'

export const UPDATE_ADMIN_START = 'UPDATE_ADMIN_START'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAILURE = 'UPDATE_ADMIN_FAILURE'

export const UPDATE_COMPANY_START = 'UPDATE_COMPANY_START'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE'

export const FETCH_ADMIN_START = 'FETCH_ADMIN_START'
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS'
export const FETCH_ADMIN_FAILURE = 'FETCH_ADMIN_FAILURE'

export const FETCH_ADMINS_START = 'FETCH_ADMINS_START'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'
export const FETCH_ADMINS_FAILURE = 'FETCH_ADMINS_FAILURE'

export const FETCH_COMPANY_START = 'FETCH_COMPANY_START'
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS'
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE'

export const FETCH_COMPANIES_START = 'FETCH_COMPANIES_START'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE'

export const FETCH_PLACE_START = 'FETCH_PLACE_START'
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS'
export const FETCH_PLACE_FAILURE = 'FETCH_PLACE_FAILURE'

export const FETCH_PLACES_START = 'FETCH_PLACES_START'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const RESET_NEW_ADMIN = 'RESET_NEW_ADMIN'
export const RESET_NEW_COMPANY = 'RESET_NEW_COMPANY'
export const RESET_EDIT_ADMIN = 'RESET_EDIT_ADMIN'
export const RESET_EDIT_COMPANY = 'RESET_EDIT_COMPANY'
